-- ============================================================================
-- Cradero — Row Level Security (RLS) Migration
-- Run this in Supabase Dashboard > SQL Editor
-- ============================================================================

-- ============================================================================
-- 1. FIX PROFILES CONSTRAINTS
-- ============================================================================

-- Add 'pending' to the role CHECK so signups don't fail
ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE profiles ADD CONSTRAINT profiles_role_check
  CHECK (role IN ('pending', 'engineer', 'manager', 'admin', 'viewer'));

-- Add tier column if it doesn't exist (frontend reads this)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'profiles' AND column_name = 'tier'
  ) THEN
    ALTER TABLE profiles ADD COLUMN tier TEXT DEFAULT 'essential';
    ALTER TABLE profiles ADD CONSTRAINT profiles_tier_check
      CHECK (tier IN ('essential', 'pro'));
  END IF;
END $$;

-- ============================================================================
-- 2. HELPER FUNCTIONS
-- ============================================================================

-- Get current user's role from profiles
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS TEXT AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid();
$$ LANGUAGE sql SECURITY DEFINER STABLE;

-- Get current user's tier from profiles
CREATE OR REPLACE FUNCTION public.get_my_tier()
RETURNS TEXT AS $$
  SELECT COALESCE(tier, 'essential') FROM public.profiles WHERE id = auth.uid();
$$ LANGUAGE sql SECURITY DEFINER STABLE;

-- ============================================================================
-- 3. CREATE MISSING TABLES (if migration 001 was not run)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.work_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  urgency text NOT NULL DEFAULT 'medium',
  submitter text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id),
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  details jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================================
-- 4. ENABLE RLS ON ALL TABLES
-- ============================================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parts_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.breakdowns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calendar_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.po_line_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pm_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pm_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 5. DROP EXISTING POLICIES (clean slate)
-- ============================================================================

-- profiles
DROP POLICY IF EXISTS "Anyone can view profiles" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Admins can update any profile" ON public.profiles;
DROP POLICY IF EXISTS "Pending users can read own profile" ON public.profiles;
DROP POLICY IF EXISTS "Active users can view profiles" ON public.profiles;
DROP POLICY IF EXISTS "Admins update any profile" ON public.profiles;

-- equipment
DROP POLICY IF EXISTS "View equipment" ON public.equipment;
DROP POLICY IF EXISTS "Staff create equipment" ON public.equipment;
DROP POLICY IF EXISTS "Staff update equipment" ON public.equipment;
DROP POLICY IF EXISTS "Admins delete equipment" ON public.equipment;

-- work_orders
DROP POLICY IF EXISTS "View work orders" ON public.work_orders;
DROP POLICY IF EXISTS "Staff create work orders" ON public.work_orders;
DROP POLICY IF EXISTS "Assigned or managers update work orders" ON public.work_orders;
DROP POLICY IF EXISTS "Staff delete work orders" ON public.work_orders;

-- parts_inventory
DROP POLICY IF EXISTS "View parts" ON public.parts_inventory;
DROP POLICY IF EXISTS "Staff manage parts" ON public.parts_inventory;
DROP POLICY IF EXISTS "Staff update parts" ON public.parts_inventory;
DROP POLICY IF EXISTS "Admins delete parts" ON public.parts_inventory;

-- breakdowns
DROP POLICY IF EXISTS "View breakdowns" ON public.breakdowns;
DROP POLICY IF EXISTS "Anyone report breakdowns" ON public.breakdowns;
DROP POLICY IF EXISTS "Staff update breakdowns" ON public.breakdowns;
DROP POLICY IF EXISTS "Staff delete breakdowns" ON public.breakdowns;

-- calendar_events
DROP POLICY IF EXISTS "View calendar" ON public.calendar_events;
DROP POLICY IF EXISTS "Staff create events" ON public.calendar_events;
DROP POLICY IF EXISTS "Creator or managers update events" ON public.calendar_events;
DROP POLICY IF EXISTS "Managers delete events" ON public.calendar_events;

-- purchase_orders
DROP POLICY IF EXISTS "View POs" ON public.purchase_orders;
DROP POLICY IF EXISTS "Staff create POs" ON public.purchase_orders;
DROP POLICY IF EXISTS "Managers update POs" ON public.purchase_orders;
DROP POLICY IF EXISTS "Staff delete POs" ON public.purchase_orders;

-- po_line_items
DROP POLICY IF EXISTS "View PO items" ON public.po_line_items;
DROP POLICY IF EXISTS "Staff create PO items" ON public.po_line_items;
DROP POLICY IF EXISTS "Managers update PO items" ON public.po_line_items;
DROP POLICY IF EXISTS "Managers delete PO items" ON public.po_line_items;

-- permits
DROP POLICY IF EXISTS "View permits" ON public.permits;
DROP POLICY IF EXISTS "Staff create permits" ON public.permits;
DROP POLICY IF EXISTS "Managers update permits" ON public.permits;

-- pm_tasks
DROP POLICY IF EXISTS "View PM tasks" ON public.pm_tasks;
DROP POLICY IF EXISTS "Staff create PM tasks" ON public.pm_tasks;
DROP POLICY IF EXISTS "Assigned or managers update PM tasks" ON public.pm_tasks;
DROP POLICY IF EXISTS "Staff delete PM tasks" ON public.pm_tasks;

-- pm_completions
DROP POLICY IF EXISTS "View PM completions" ON public.pm_completions;
DROP POLICY IF EXISTS "Staff log PM completions" ON public.pm_completions;

-- work_requests
DROP POLICY IF EXISTS "Authenticated users can read work_requests" ON public.work_requests;
DROP POLICY IF EXISTS "Authenticated users can insert work_requests" ON public.work_requests;
DROP POLICY IF EXISTS "Authenticated users can update work_requests" ON public.work_requests;
DROP POLICY IF EXISTS "View work requests" ON public.work_requests;
DROP POLICY IF EXISTS "Submit work requests" ON public.work_requests;
DROP POLICY IF EXISTS "Managers approve work requests" ON public.work_requests;

-- audit_log
DROP POLICY IF EXISTS "Authenticated users can insert audit_log" ON public.audit_log;
DROP POLICY IF EXISTS "Admins can read audit_log" ON public.audit_log;
DROP POLICY IF EXISTS "Insert audit entries" ON public.audit_log;
DROP POLICY IF EXISTS "Admins read audit log" ON public.audit_log;

-- ============================================================================
-- 6. CREATE POLICIES
-- ============================================================================

-- ---------------------------------------------------------------------------
-- PROFILES
-- ---------------------------------------------------------------------------

-- Pending users can read ONLY their own profile (to check their role/status)
CREATE POLICY "Pending users can read own profile"
  ON public.profiles FOR SELECT
  TO authenticated
  USING (auth.uid() = id);

-- Active (non-pending) users can view all profiles (employee directory)
CREATE POLICY "Active users can view profiles"
  ON public.profiles FOR SELECT
  TO authenticated
  USING (public.get_my_role() != 'pending');

-- Users can update their own profile (name, phone, etc.)
CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- Admins can update any profile (role changes, tier changes)
CREATE POLICY "Admins update any profile"
  ON public.profiles FOR UPDATE
  TO authenticated
  USING (public.get_my_role() = 'admin')
  WITH CHECK (public.get_my_role() = 'admin');

-- ---------------------------------------------------------------------------
-- EQUIPMENT
-- ---------------------------------------------------------------------------

-- Non-pending users can view equipment
CREATE POLICY "View equipment"
  ON public.equipment FOR SELECT
  TO authenticated
  USING (public.get_my_role() != 'pending');

-- Engineers, managers, admins can create equipment
CREATE POLICY "Staff create equipment"
  ON public.equipment FOR INSERT
  TO authenticated
  WITH CHECK (public.get_my_role() IN ('engineer', 'manager', 'admin'));

-- Engineers, managers, admins can update equipment
CREATE POLICY "Staff update equipment"
  ON public.equipment FOR UPDATE
  TO authenticated
  USING (public.get_my_role() IN ('engineer', 'manager', 'admin'))
  WITH CHECK (public.get_my_role() IN ('engineer', 'manager', 'admin'));

-- Only admins can delete equipment
CREATE POLICY "Admins delete equipment"
  ON public.equipment FOR DELETE
  TO authenticated
  USING (public.get_my_role() = 'admin');

-- ---------------------------------------------------------------------------
-- WORK ORDERS
-- ---------------------------------------------------------------------------

-- Non-pending users can view work orders
CREATE POLICY "View work orders"
  ON public.work_orders FOR SELECT
  TO authenticated
  USING (public.get_my_role() != 'pending');

-- Engineers, managers, admins can create work orders
CREATE POLICY "Staff create work orders"
  ON public.work_orders FOR INSERT
  TO authenticated
  WITH CHECK (public.get_my_role() IN ('engineer', 'manager', 'admin'));

-- Assigned user or managers/admins can update work orders
CREATE POLICY "Assigned or managers update work orders"
  ON public.work_orders FOR UPDATE
  TO authenticated
  USING (
    auth.uid() = assigned_to
    OR public.get_my_role() IN ('manager', 'admin')
  )
  WITH CHECK (
    auth.uid() = assigned_to
    OR public.get_my_role() IN ('manager', 'admin')
  );

-- Managers and admins can delete work orders
CREATE POLICY "Staff delete work orders"
  ON public.work_orders FOR DELETE
  TO authenticated
  USING (public.get_my_role() IN ('manager', 'admin'));

-- ---------------------------------------------------------------------------
-- PARTS INVENTORY
-- ---------------------------------------------------------------------------

-- Non-pending users can view parts
CREATE POLICY "View parts"
  ON public.parts_inventory FOR SELECT
  TO authenticated
  USING (public.get_my_role() != 'pending');

-- Engineers, managers, admins can create parts
CREATE POLICY "Staff manage parts"
  ON public.parts_inventory FOR INSERT
  TO authenticated
  WITH CHECK (public.get_my_role() IN ('engineer', 'manager', 'admin'));

-- Engineers, managers, admins can update parts
CREATE POLICY "Staff update parts"
  ON public.parts_inventory FOR UPDATE
  TO authenticated
  USING (public.get_my_role() IN ('engineer', 'manager', 'admin'))
  WITH CHECK (public.get_my_role() IN ('engineer', 'manager', 'admin'));

-- Only admins can delete parts
CREATE POLICY "Admins delete parts"
  ON public.parts_inventory FOR DELETE
  TO authenticated
  USING (public.get_my_role() = 'admin');

-- ---------------------------------------------------------------------------
-- BREAKDOWNS
-- ---------------------------------------------------------------------------

-- Non-pending users can view breakdowns
CREATE POLICY "View breakdowns"
  ON public.breakdowns FOR SELECT
  TO authenticated
  USING (public.get_my_role() != 'pending');

-- Any non-pending user can report breakdowns
CREATE POLICY "Anyone report breakdowns"
  ON public.breakdowns FOR INSERT
  TO authenticated
  WITH CHECK (public.get_my_role() != 'pending');

-- Engineers, managers, admins can update breakdowns
CREATE POLICY "Staff update breakdowns"
  ON public.breakdowns FOR UPDATE
  TO authenticated
  USING (public.get_my_role() IN ('engineer', 'manager', 'admin'))
  WITH CHECK (public.get_my_role() IN ('engineer', 'manager', 'admin'));

-- Managers and admins can delete breakdowns
CREATE POLICY "Staff delete breakdowns"
  ON public.breakdowns FOR DELETE
  TO authenticated
  USING (public.get_my_role() IN ('manager', 'admin'));

-- ---------------------------------------------------------------------------
-- CALENDAR EVENTS (Pro-only)
-- ---------------------------------------------------------------------------

-- Non-pending Pro users can view calendar events
CREATE POLICY "View calendar"
  ON public.calendar_events FOR SELECT
  TO authenticated
  USING (
    public.get_my_role() != 'pending'
    AND public.get_my_tier() = 'pro'
  );

-- Pro engineers, managers, admins can create events
CREATE POLICY "Staff create events"
  ON public.calendar_events FOR INSERT
  TO authenticated
  WITH CHECK (
    public.get_my_role() IN ('engineer', 'manager', 'admin')
    AND public.get_my_tier() = 'pro'
  );

-- Pro creator or managers/admins can update events
CREATE POLICY "Creator or managers update events"
  ON public.calendar_events FOR UPDATE
  TO authenticated
  USING (
    public.get_my_tier() = 'pro'
    AND (auth.uid() = created_by OR public.get_my_role() IN ('manager', 'admin'))
  )
  WITH CHECK (
    public.get_my_tier() = 'pro'
    AND (auth.uid() = created_by OR public.get_my_role() IN ('manager', 'admin'))
  );

-- Pro managers/admins can delete events
CREATE POLICY "Managers delete events"
  ON public.calendar_events FOR DELETE
  TO authenticated
  USING (
    public.get_my_role() IN ('manager', 'admin')
    AND public.get_my_tier() = 'pro'
  );

-- ---------------------------------------------------------------------------
-- PURCHASE ORDERS (Pro-only)
-- ---------------------------------------------------------------------------

-- Non-pending Pro users can view POs
CREATE POLICY "View POs"
  ON public.purchase_orders FOR SELECT
  TO authenticated
  USING (
    public.get_my_role() != 'pending'
    AND public.get_my_tier() = 'pro'
  );

-- Pro engineers, managers, admins can create POs
CREATE POLICY "Staff create POs"
  ON public.purchase_orders FOR INSERT
  TO authenticated
  WITH CHECK (
    public.get_my_role() IN ('engineer', 'manager', 'admin')
    AND public.get_my_tier() = 'pro'
  );

-- Pro managers/admins can update POs (approve, status changes)
CREATE POLICY "Managers update POs"
  ON public.purchase_orders FOR UPDATE
  TO authenticated
  USING (
    public.get_my_role() IN ('manager', 'admin')
    AND public.get_my_tier() = 'pro'
  )
  WITH CHECK (
    public.get_my_role() IN ('manager', 'admin')
    AND public.get_my_tier() = 'pro'
  );

-- Pro managers/admins can delete POs
CREATE POLICY "Staff delete POs"
  ON public.purchase_orders FOR DELETE
  TO authenticated
  USING (
    public.get_my_role() IN ('manager', 'admin')
    AND public.get_my_tier() = 'pro'
  );

-- ---------------------------------------------------------------------------
-- PO LINE ITEMS (Pro-only, follows purchase_orders access)
-- ---------------------------------------------------------------------------

-- Non-pending Pro users can view PO line items
CREATE POLICY "View PO items"
  ON public.po_line_items FOR SELECT
  TO authenticated
  USING (
    public.get_my_role() != 'pending'
    AND public.get_my_tier() = 'pro'
  );

-- Pro engineers, managers, admins can create PO line items
CREATE POLICY "Staff create PO items"
  ON public.po_line_items FOR INSERT
  TO authenticated
  WITH CHECK (
    public.get_my_role() IN ('engineer', 'manager', 'admin')
    AND public.get_my_tier() = 'pro'
  );

-- Pro managers/admins can update PO line items
CREATE POLICY "Managers update PO items"
  ON public.po_line_items FOR UPDATE
  TO authenticated
  USING (
    public.get_my_role() IN ('manager', 'admin')
    AND public.get_my_tier() = 'pro'
  )
  WITH CHECK (
    public.get_my_role() IN ('manager', 'admin')
    AND public.get_my_tier() = 'pro'
  );

-- Pro managers/admins can delete PO line items
CREATE POLICY "Managers delete PO items"
  ON public.po_line_items FOR DELETE
  TO authenticated
  USING (
    public.get_my_role() IN ('manager', 'admin')
    AND public.get_my_tier() = 'pro'
  );

-- ---------------------------------------------------------------------------
-- PERMITS (Pro-only)
-- ---------------------------------------------------------------------------

-- Non-pending Pro users can view permits
CREATE POLICY "View permits"
  ON public.permits FOR SELECT
  TO authenticated
  USING (
    public.get_my_role() != 'pending'
    AND public.get_my_tier() = 'pro'
  );

-- Pro engineers, managers, admins can create permits
CREATE POLICY "Staff create permits"
  ON public.permits FOR INSERT
  TO authenticated
  WITH CHECK (
    public.get_my_role() IN ('engineer', 'manager', 'admin')
    AND public.get_my_tier() = 'pro'
  );

-- Pro managers/admins can update permits (close, approve)
CREATE POLICY "Managers update permits"
  ON public.permits FOR UPDATE
  TO authenticated
  USING (
    public.get_my_role() IN ('manager', 'admin')
    AND public.get_my_tier() = 'pro'
  )
  WITH CHECK (
    public.get_my_role() IN ('manager', 'admin')
    AND public.get_my_tier() = 'pro'
  );

-- ---------------------------------------------------------------------------
-- PM TASKS
-- ---------------------------------------------------------------------------

-- Non-pending users can view PM tasks
CREATE POLICY "View PM tasks"
  ON public.pm_tasks FOR SELECT
  TO authenticated
  USING (public.get_my_role() != 'pending');

-- Engineers, managers, admins can create PM tasks
CREATE POLICY "Staff create PM tasks"
  ON public.pm_tasks FOR INSERT
  TO authenticated
  WITH CHECK (public.get_my_role() IN ('engineer', 'manager', 'admin'));

-- Assigned user or managers/admins can update PM tasks
CREATE POLICY "Assigned or managers update PM tasks"
  ON public.pm_tasks FOR UPDATE
  TO authenticated
  USING (
    auth.uid() = assigned_to
    OR public.get_my_role() IN ('manager', 'admin')
  )
  WITH CHECK (
    auth.uid() = assigned_to
    OR public.get_my_role() IN ('manager', 'admin')
  );

-- Managers and admins can delete PM tasks
CREATE POLICY "Staff delete PM tasks"
  ON public.pm_tasks FOR DELETE
  TO authenticated
  USING (public.get_my_role() IN ('manager', 'admin'));

-- ---------------------------------------------------------------------------
-- PM COMPLETIONS
-- ---------------------------------------------------------------------------

-- Non-pending users can view PM completions
CREATE POLICY "View PM completions"
  ON public.pm_completions FOR SELECT
  TO authenticated
  USING (public.get_my_role() != 'pending');

-- Engineers, managers, admins can log PM completions
CREATE POLICY "Staff log PM completions"
  ON public.pm_completions FOR INSERT
  TO authenticated
  WITH CHECK (public.get_my_role() IN ('engineer', 'manager', 'admin'));

-- ---------------------------------------------------------------------------
-- WORK REQUESTS
-- ---------------------------------------------------------------------------

-- Non-pending users can view work requests
CREATE POLICY "View work requests"
  ON public.work_requests FOR SELECT
  TO authenticated
  USING (public.get_my_role() != 'pending');

-- Any non-pending user can submit work requests
CREATE POLICY "Submit work requests"
  ON public.work_requests FOR INSERT
  TO authenticated
  WITH CHECK (public.get_my_role() != 'pending');

-- Only managers and admins can update work requests (approve/decline)
CREATE POLICY "Managers approve work requests"
  ON public.work_requests FOR UPDATE
  TO authenticated
  USING (public.get_my_role() IN ('manager', 'admin'))
  WITH CHECK (public.get_my_role() IN ('manager', 'admin'));

-- ---------------------------------------------------------------------------
-- AUDIT LOG
-- ---------------------------------------------------------------------------

-- Any authenticated user can insert audit entries (for their own user_id)
CREATE POLICY "Insert audit entries"
  ON public.audit_log FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

-- Only admins can read audit log
CREATE POLICY "Admins read audit log"
  ON public.audit_log FOR SELECT
  TO authenticated
  USING (public.get_my_role() = 'admin');

-- ============================================================================
-- DONE — Verify in Supabase Dashboard > Table Editor
-- Each table should show a lock icon indicating RLS is enabled.
-- ============================================================================
